import Head from 'next/head'
import styles from '../styles/Home.module.css'

export const getStaticProps = async () => {
  const res = await fetch('http://localhost:8080/properties')
  const data = await res.json()
  const lastValue = (data.values.soilMoisture).pop()

  // Return latest value
  return {
    props: { soilMoisture: lastValue.moisture_percentage }
  }
}

const Home = ({ soilMoisture }) => {
  let procentage = Math.round(soilMoisture)  
  let healtyLabel

  // Fixa till - om högre soil moisture än 50 % --> healty
  if (procentage >= 50) {
    healtyLabel = (
      <p className={styles.healty}>Healty</p>
     )

  } else {
    healtyLabel = (
      <p className={styles.unhealty}>Unhealty</p>
     )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>IoT Garden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Gardening with Raspberry Pi Pico</h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Date</h2>
            <p className={styles.value}>20:00</p>
          </div>

          <div className={styles.card}>
            <h2>Soil Moisture</h2>
            <p className={styles.procentage}> {procentage}%</p>
            
            <div className={styles.procontainer}>
              <div className={styles.promesure} style={{width: procentage + '%'}}></div>
            </div>
            
            <div className={styles.status}>
              <p>Status</p>
              {healtyLabel}
            </div>
            

          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        Johanna Wirell - 1DV027
      </footer>
    </div>
  )
}


export default Home;
